/**
 * @author tknight-dev
 */

export class DOM {
	protected static elementAlive: HTMLElement;
	protected static elementControls: HTMLElement;
	protected static elementControlsBackward: HTMLElement;
	protected static elementControlsForward: HTMLElement;
	protected static elementControlsPause: HTMLElement;
	protected static elementControlsPlay: HTMLElement;
	protected static elementControlsReset: HTMLElement;
	protected static elementCounts: HTMLElement;
	protected static elementDataContainer: HTMLElement;
	protected static elementDead: HTMLElement;
	protected static elementEdit: HTMLElement;
	protected static elementEditAddDeath: HTMLElement;
	protected static elementEditAddLife: HTMLElement;
	protected static elementEditMove: HTMLElement;
	protected static elementEditRemove: HTMLElement;
	protected static elementEditSave: HTMLElement;
	protected static elementEditScreenshot: HTMLElement;
	protected static elementEditUpload: HTMLElement;
	protected static elementError: HTMLElement;
	protected static elementFile: HTMLElement;
	protected static elementFPS: HTMLElement;
	protected static elementFullscreen: HTMLElement;
	protected static elementGame: HTMLElement;
	protected static elementGamepadNotCompatible: HTMLElement;
	protected static elementGameOver: HTMLElement;
	protected static elementHomeostatic: HTMLElement;
	protected static elementIPSRequested: HTMLElement;
	protected static elementLogo: HTMLElement;
	protected static elementMenu: HTMLElement;
	protected static elementMenuContent: HTMLElement;
	protected static elementMenuRules: HTMLElement;
	protected static elementMenuSettings: HTMLElement;
	protected static elementPerformance: HTMLElement;
	protected static elementPerformanceAll: HTMLElement;
	protected static elementPerformanceBus: HTMLElement;
	protected static elementPerformanceCalc: HTMLElement;
	protected static elementPerformanceCtV: HTMLElement;
	protected static elementPerformanceDraw: HTMLElement;
	protected static elementPerformanceHomeostatis: HTMLElement;
	protected static elementPerformanceNeighbors: HTMLElement;
	protected static elementPerformanceState: HTMLElement;
	protected static elementRotator: HTMLElement;
	protected static elementRules: HTMLElement;
	protected static elementRulesClose: HTMLButtonElement;
	protected static elementSettings: HTMLElement;
	protected static elementSettingsApply: HTMLButtonElement;
	protected static elementSettingsCancel: HTMLButtonElement;
	protected static elementSettingsValueCPUSpinOutProtection: HTMLInputElement;
	protected static elementSettingsValueDrawDeadCells: HTMLInputElement;
	protected static elementSettingsValueDrawGrid: HTMLInputElement;
	protected static elementSettingsValueFPS: HTMLInputElement;
	protected static elementSettingsValueFPSShow: HTMLInputElement;
	protected static elementSettingsValueHomeostaticPause: HTMLInputElement;
	protected static elementSettingsValueIPS: HTMLInputElement;
	protected static elementSettingsValueOrientationAutoRotate: HTMLInputElement;
	protected static elementSettingsValueResolution: HTMLInputElement;
	protected static elementSettingsValueResolutionScaleType: HTMLInputElement;
	protected static elementSettingsValueSeedRandom: HTMLInputElement;
	protected static elementSettingsValueStatsShowAliveDead: HTMLInputElement;
	protected static elementSettingsValueStatsShowPerformance: HTMLInputElement;
	protected static elementSettingsValueTableSize: HTMLInputElement;
	protected static elementSpinner: HTMLElement;
	protected static elementSpinout: HTMLElement;
	protected static elementStats: HTMLElement;
	protected static elementStatsC: HTMLElement;
	protected static elementStatsCPS: HTMLElement;
	protected static elementStatsCPSAll: HTMLElement;
	protected static elementVersion: HTMLElement;
	protected static elementVideo: HTMLElement;
	protected static elementVideoCanvases: HTMLCanvasElement[]; // Must be fetched by the GamingCanvas after initialization
	protected static elementVideoInteractive: HTMLElement;
	protected static elementWebGLNotSupported: HTMLElement;

	public static initializeDOM(): void {
		DOM.elementAlive = <HTMLElement>document.getElementById('alive');
		DOM.elementControls = <HTMLElement>document.getElementById('controls');
		DOM.elementControlsBackward = <HTMLElement>document.getElementById('backward');
		DOM.elementControlsForward = <HTMLElement>document.getElementById('forward');
		DOM.elementControlsPause = <HTMLElement>document.getElementById('pause');
		DOM.elementControlsPlay = <HTMLElement>document.getElementById('play');
		DOM.elementControlsReset = <HTMLElement>document.getElementById('reset');
		DOM.elementCounts = <HTMLElement>document.getElementById('counts');
		DOM.elementDataContainer = <HTMLElement>document.getElementById('data-container');
		DOM.elementDead = <HTMLCanvasElement>document.getElementById('dead');
		DOM.elementEditAddDeath = <HTMLElement>document.getElementById('edit-add-death');
		DOM.elementEditAddLife = <HTMLElement>document.getElementById('edit-add-life');
		DOM.elementEditMove = <HTMLElement>document.getElementById('edit-move');
		DOM.elementEditRemove = <HTMLElement>document.getElementById('edit-remove');
		DOM.elementEditSave = <HTMLElement>document.getElementById('edit-save');
		DOM.elementEditScreenshot = <HTMLElement>document.getElementById('edit-screenshot');
		DOM.elementEditUpload = <HTMLElement>document.getElementById('edit-upload');
		DOM.elementError = <HTMLElement>document.getElementById('error');
		DOM.elementFile = <HTMLElement>document.getElementById('file');
		DOM.elementFPS = <HTMLElement>document.getElementById('fps');
		DOM.elementFullscreen = <HTMLElement>document.getElementById('fullscreen');
		DOM.elementGame = <HTMLElement>document.getElementById('game');
		DOM.elementGamepadNotCompatible = <HTMLElement>document.getElementById('gamepad-not-compatible');
		DOM.elementGameOver = <HTMLElement>document.getElementById('game-over');
		DOM.elementHomeostatic = <HTMLElement>document.getElementById('homeostatic');
		DOM.elementIPSRequested = <HTMLElement>document.getElementById('ips-requested');
		DOM.elementLogo = <HTMLElement>document.getElementById('logo');
		DOM.elementMenu = <HTMLElement>document.getElementById('info-menu');
		DOM.elementMenuContent = <HTMLElement>document.getElementById('menu-content');
		DOM.elementMenuRules = <HTMLElement>document.getElementById('info-rules');
		DOM.elementMenuSettings = <HTMLElement>document.getElementById('info-settings');
		DOM.elementPerformance = <HTMLElement>document.getElementById('performance');
		DOM.elementPerformanceAll = <HTMLElement>document.getElementById('performance-all');
		DOM.elementPerformanceBus = <HTMLElement>document.getElementById('performance-bus');
		DOM.elementPerformanceCalc = <HTMLElement>document.getElementById('performance-calc');
		DOM.elementPerformanceCtV = <HTMLElement>document.getElementById('performance-ctv');
		DOM.elementPerformanceDraw = <HTMLElement>document.getElementById('performance-draw');
		DOM.elementPerformanceHomeostatis = <HTMLElement>document.getElementById('performance-homeostatis');
		DOM.elementPerformanceNeighbors = <HTMLElement>document.getElementById('performance-neighbors');
		DOM.elementPerformanceState = <HTMLElement>document.getElementById('performance-state');
		DOM.elementSettings = <HTMLElement>document.getElementById('settings');
		DOM.elementRotator = <HTMLElement>document.getElementById('rotator');
		DOM.elementRules = <HTMLButtonElement>document.getElementById('rules');
		DOM.elementRulesClose = <HTMLButtonElement>document.getElementById('rules-close');
		DOM.elementSettingsApply = <HTMLButtonElement>document.getElementById('settings-apply');
		DOM.elementSettingsCancel = <HTMLButtonElement>document.getElementById('settings-cancel');
		DOM.elementSettingsValueCPUSpinOutProtection = <HTMLInputElement>document.getElementById('settings-value-cpu-spin-out-protection');
		DOM.elementSettingsValueDrawDeadCells = <HTMLInputElement>document.getElementById('settings-value-draw-dead-cells');
		DOM.elementSettingsValueDrawGrid = <HTMLInputElement>document.getElementById('settings-value-draw-grid');
		DOM.elementSettingsValueFPS = <HTMLInputElement>document.getElementById('settings-value-fps');
		DOM.elementSettingsValueFPSShow = <HTMLInputElement>document.getElementById('settings-value-fps-show');
		DOM.elementSettingsValueHomeostaticPause = <HTMLInputElement>document.getElementById('settings-value-homeostatic-pause');
		DOM.elementSettingsValueIPS = <HTMLInputElement>document.getElementById('settings-value-ips');
		DOM.elementSettingsValueOrientationAutoRotate = <HTMLInputElement>document.getElementById('settings-value-orientation-auto-rotate');
		DOM.elementSettingsValueResolution = <HTMLInputElement>document.getElementById('settings-value-resolution');
		DOM.elementSettingsValueResolutionScaleType = <HTMLInputElement>document.getElementById('settings-value-resolution-scale-type');
		DOM.elementSettingsValueSeedRandom = <HTMLInputElement>document.getElementById('settings-value-seed-random');
		DOM.elementSettingsValueStatsShowAliveDead = <HTMLInputElement>document.getElementById('settings-value-stats-show-alive-dead');
		DOM.elementSettingsValueStatsShowPerformance = <HTMLInputElement>document.getElementById('settings-value-stats-show-performance');
		DOM.elementSettingsValueTableSize = <HTMLInputElement>document.getElementById('settings-value-table-size');
		DOM.elementSpinner = <HTMLElement>document.getElementById('spinner');
		DOM.elementSpinout = <HTMLElement>document.getElementById('spinout');
		DOM.elementStats = <HTMLElement>document.getElementById('stats');
		DOM.elementStatsC = <HTMLElement>document.getElementById('c');
		DOM.elementStatsCPS = <HTMLElement>document.getElementById('cps');
		DOM.elementStatsCPSAll = <HTMLElement>document.getElementById('cps-all');
		DOM.elementVersion = <HTMLElement>document.getElementById('version');
		DOM.elementVideo = <HTMLElement>document.getElementById('video');
		DOM.elementVideoInteractive = <HTMLElement>document.getElementById('video-interactive');
		DOM.elementWebGLNotSupported = <HTMLElement>document.getElementById('webgl-not-supported');
	}
}
